services:
  - type: web
    name: autofilterbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: autofilterbot
      - key: FILE_CHANNEL
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: ADMINS
        sync: false
      - key: MAX_RESULTS
        value: "10"
